language: cpp
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=unit && CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=integration && CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=vera && CC=gcc-7 && CXX=g++-7"
    #- os: linux
    #  env:
    #    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
    - eval "${MATRIX_EVAL}"
addons:
    apt:
      sources:
          - ubuntu-toolchain-r-test
      packages:
          - g++-7
          - libboost-all-dev
install:
    - git clone https://github.com/google/gumbo-parser.git
    - cd gumbo-parser
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - cd ../
script:
    - scripts/run-tests.sh "${SUITE}"
