language: cpp
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=unit && CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=integration && CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=benchmarks && CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="SUITE=unit && CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - clang-tidy-6.0
      env:
        - MATRIX_EVAL="SUITE=clang-tidy && CC=clang-6.0 && CXX=clang++-6.0"
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - git clone https://github.com/llvm-mirror/clang-tools-extra/
        - sudo cp clang-tools-extra/clang-tidy/tool/run-clang-tidy.py /usr/local/bin
        - cd build
        - cp ../.clang-tidy ./
        - ../scripts/clang-tidy.sh
    - os: linux
      env:
        - vera++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lua5.1
            - liblua5.1
            - libluabind-dev
            - libtcl8.6
            - tcl-dev
            - libboost-all-dev
      install:
        - git clone https://bitbucket.org/verateam/vera.git
        - cd vera
        - mkdir build
        - cd build
        - cmake -D VERA_USE_SYSTEM_BOOST:BOOL=ON ..
        - make
        - sudo make install
        - cd ../../
      script:
        - scripts/vera.sh
before_install:
  - eval "${MATRIX_EVAL}"
  - |
    # Install conan
    export PATH=$HOME/.local/bin:$PATH
    pip install --user conan
    conan profile new default --detect
    conan profile update settings.compiler.libcxx=libstdc++11 default
    if [[ $CXX = *"clang"* ]]; then
        conan profile update env.CC=clang-6.0 default
        conan profile update env.CXX=clang++-6.0 default
    fi
    conan remote add irkit https://api.bintray.com/conan/elshize/irkit
    conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
    conan remote add cliutils https://api.bintray.com/conan/cliutils/CLI11
    conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    conan remote add manu https://api.bintray.com/conan/manu343726/conan-packages
  - |
    # Print environment
    which $CXX
    which $CC
    $CXX --version
    which cmake
    cmake --version
    conan --version
    conan profile show default
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-all-dev
install:
  - |
    # Configure project
    cd ${TRAVIS_BUILD_DIR}
    mkdir build && cd build
    conan install .. --build=missing -o irkit:use_system_boost=True
script:
  - cd ${TRAVIS_BUILD_DIR}
  - scripts/run-tests.sh "${SUITE}"
