language: cpp
matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=unit && CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=integration && CC=gcc-7 && CXX=g++-7"
    - os: linux
      env:
        - MATRIX_EVAL="SUITE=benchmarks && CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="SUITE=unit && CC=clang-6.0 && CXX=clang++-6.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - g++-7
            - libboost-all-dev
            - clang-6.0
            - clang-tidy-6.0
      env:
        - MATRIX_EVAL="SUITE=clang-tidy && CC=gcc-7 && CXX=g++-7"
      script:
        - git clone https://github.com/llvm-mirror/clang-tools-extra/
        - sudo cp clang-tools-extra/clang-tidy/tool/run-clang-tidy.py /usr/local/bin
        - mkdir tidy && cd tidy
        - cp ../.clang-tidy ./
        - ../scripts/clang-tidy.sh
    - os: linux
      env:
        - vera++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lua5.1
            - liblua5.1
            - libluabind-dev
            - libtcl8.6
            - tcl-dev
            - libboost-all-dev
      install:
        - git clone https://bitbucket.org/verateam/vera.git
        - cd vera
        - mkdir build
        - cd build
        - cmake -D VERA_USE_SYSTEM_BOOST:BOOL=ON ..
        - make
        - sudo make install
        - cd ../../
      script:
        - scripts/vera.sh
before_install:
    - eval "${MATRIX_EVAL}"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-all-dev
install:
  - sudo pip install conan
  - conan remote add irkit https://api.bintray.com/conan/elshize/irkit
  - conan install . --build=missing
script:
  - scripts/run-tests.sh "${SUITE}"
