language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-6.0
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
before_install:
    - eval "${MATRIX_EVAL}"
install:
    - git clone https://github.com/google/gumbo-parser.git
    - cd gumbo-parser
    - ./autogen.sh
    - ./configure
    - make
    - sudo make install
    - cd ../
script:
    - cmake .
    - cmake --build .
    - ctest
